Ductus.FluentDocker/Services/Extensions/NetworkExtensions.cs

Added a better error message for the case when the specified container port is not found (previously NRE was thrown which is not very helpful).

Better Error Message For WaitForPort

---

Ductus.FluentDocker/Commands/Compose.cs

Fixes a problem where file paths/names with spaces didn't work.
Note: I have not run the tests!  I'll be happy to run them if you can assist me in getting them working on my machine.  There seems to be some necessary setup that I don't have and can't find documented anywhere.

Add double-quotes around composeFile everywhere.

---

Ductus.FluentDocker.Tests/FluentApiTests/FluentContainerBasicTests.cs
Ductus.FluentDocker/Builders/ContainerBuilder.cs
Ductus.FluentDocker/Model/Containers/ContainerCreateParams.cs
Ductus.FluentDocker/Model/Containers/ContainerState.cs
Ductus.FluentDocker/Model/Containers/Health.cs
Ductus.FluentDocker/Model/Containers/HealthState.cs

A common feature in Dockerfiles is to define a custom health check. This PR includes the ability to return some basic health check information from the existing `GetConfiguration()` command.
In order to include a test to cover this new model mapping, a new method `.HealthCheck(string command)` has been added to the `ContainerBuilder` since the `postgress` image used for testing doesnt expose a health configuration of its own.

Add model support for returning health check in config.

---

Ductus.FluentDocker/Model/Containers/ContainerState.cs

Windows Containers sometimes exit with 3221225725 (depending on the method of process exiting) causing parsing error in Json.Net.
I am happy if you would like to discuss other solutions to this bug.
e.g.
> docker inspect 2b8
returns
```
[
{
"Id": "2b832e9e8d82158162d0cd289900f951c0074d496003b649965f7631f4855d78",
"Created": "2019-07-21T00:27:12.1995388Z",
"Path": "powershell",
"Args": [ ],
"State": {
"Status": "exited",
"Running": false,
"Paused": false,
"Restarting": false,
"OOMKilled": false,
"Dead": false,
"Pid": 0,
"ExitCode": 3221225786,
"Error": "",
"StartedAt": "2019-07-21T00:27:18.5270944Z",
"FinishedAt": "2019-07-21T10:29:56.1215523+10:00",
...
```
which fluentDocker then throws with
```
Unhandled Exception: Newtonsoft.Json.JsonReaderException: JSON integer 3221225786 is too …
```

Update ExitCode to long. 

---

Ductus.FluentDocker/Services/Impl/DockerContainerService.cs

TL;DR:
Removing a `RUNNING` docker container must not be allowed, unless `force=true` is used.
----
During #113 I've noticed that executing:
```
Environment.SetEnvironmentVariable("DOCKER_HOST", "ax-docker02:2375");
var composition = new Builder()
.UseContainer()
.UseCompose()
.FromFile("testcase1.yml")
.Build();
composition.Start();
composition.Containers.ToList().ForEach(c => c.Remove()); // force = false
```
will remove `RUNNING` containers, although the optional `force` parameter is not used.
The API shall reflect the behavior of the docker client, where `docker rm <containerid>` is not permitted if the container is running.

Running containers must not be stopped unless force is used (Issue #113)

---

Ductus.FluentDocker/Builders/ContainerBuilder.cs
Ductus.FluentDocker/Model/Builders/ContainerBuilderConfig.cs
Ductus.FluentDocker/Services/Extensions/ContainerExtensions.cs

This feature covers a usecase, when we start a docker container and wait for it to be in a healthy state.

Feature: waitForHealthy

---

Ductus.FluentDocker/Builders/ContainerBuilder.cs
Ductus.FluentDocker/Model/Containers/ContainerCreateParams.cs
appveyor.yml

This relates to Issue #130 where it was not possible to override **all** aspects of the _HEALTCHECK_ section in runtime.

Fix health check FluentAPI

---

Ductus.FluentDocker.Tests/Model/Containers/ContainerCreateParamsTests.cs
Ductus.FluentDocker/Builders/ContainerBuilder.cs
Ductus.FluentDocker/Model/Containers/ContainerCreateParams.cs
Ductus.FluentDocker/Model/Containers/ContainerRuntime.cs
appveyor.yml

It is now possible to do 
```cs
ContainerBuilder.UseRuntime(ContainerRuntime.Nvidia);
```
this will add _--runtime=nvidia_ when creating the container. The only custom runtime is ContainerRuntime.Nvidia as of now.
This is to solve Issue #132

Added support for custom runtime in FluentAPI (Issue #132).

---

Ductus.FluentDocker.Tests/ProcessResponseParsersTests/NetworkLsResponseParserTests.cs
Ductus.FluentDocker/Commands/Network.cs
Ductus.FluentDocker/Executors/Parsers/NetworkInspectResponseParser.cs
Ductus.FluentDocker/Executors/Parsers/NetworkLsResponseParser.cs

NetworkLs: Fix parsing of CreatedAt DateTime 
- Move parsing logic out of Network class to a parser
- Fix parser to support negative timezones for CreatedAt date
See #143

NetworkLs: Fix parsing of CreatedAt

---

Ductus.FluentDocker.Tests/CommandTests/DockerClientCommandTests.cs
Ductus.FluentDocker.Tests/ServiceTests/ContainerServiceBasicTests.cs
Ductus.FluentDocker/Commands/Client.cs
Ductus.FluentDocker/Executors/Parsers/ClientInspectContainersResponseParser.cs
Ductus.FluentDocker/Model/Containers/Container.cs
Ductus.FluentDocker/Services/Impl/DockerHostService.cs

DockerHostService.GetContainers:
Improve performance by running one inspect command for multiple containers:
docker inspect id1 id2 ... idN
containers cnt | docker cli, ms | GetContainers before, ms | GetContainers after, ms
1 | 95 | 400 | 400
2 | 105 | 545 | 405
8 | 125 | 700 | 440
16 | 160 | 1020 | 460
32 | 210 | 1650 | 520
See #145

Improve GetContainers performance

---

Ductus.FluentDocker.Tests/Ductus.FluentDocker.Tests.csproj
Ductus.FluentDocker.Tests/ExtensionTests/EnironmentExtensionTests.cs
Ductus.FluentDocker.Tests/ProcessTests/ProcessEnvironmentTest.cs
Ductus.FluentDocker.Tests/Resources/Scripts/envtest.bat
Ductus.FluentDocker.Tests/Resources/Scripts/envtest.sh
Ductus.FluentDocker/Builders/CompositeBuilder.cs
Ductus.FluentDocker/Commands/Compose.cs
Ductus.FluentDocker/Executors/ProcessExecutor.cs
Ductus.FluentDocker/Extensions/EnvironmentExtensions.cs
Ductus.FluentDocker/Model/Compose/DockerComposeConfig.cs
Ductus.FluentDocker/Services/Impl/DockerComposeCompositeService.cs

This relates to Issue #147 where it is possible to pass environment to all compose commands and therefore it may be possible to use those environment variables in the docker-compose file. Since each invocation is shielded in the `ProcessExecutor` the environment variables are local for each invocation.
Given:
```yaml
build:
context: .
labels:
- "com.example.description=${DESCRIPTION}"
- "${CUSTOM_NAME}=${CUSTOM_VALUE}"
```
Set environment for the Compose in the _FluentAPI_:
```cs
Fd.UseContainer()
.WithEnvironment()	
.UseCompose()
.FromFile(ComposeFilePaths)
.ServiceName(ComposeProjectName)
.WithEnvironment(
$"DESCRIPTION={description}",
$"CUSTOM_NAME={buildname}",
$"CUSTOM_VALUE={buildtag}")	
.RemoveOrphans()	
.WaitForPort(ComposeProjectName, $"{PrivateServicePort.Port}/tcp", …
```

Feature pass environment to compose

---

Ductus.FluentDocker.Tests/ServiceTests/DockerComposeTests.cs
Ductus.FluentDocker/Builders/CompositeBuilder.cs
Ductus.FluentDocker/Services/Impl/DockerComposeCompositeService.cs

Since we can have multiple `docker-compose.yml` files the error messages at various places should be corrected. Otherwise we get error messages like this one:
```
Ductus.FluentDocker.Common.FluentDockerException: 
Could not start composite service System.Collections.Generic.List`1[System.String] - result: build path 
```

Fix error messages docker-compose files

---

.vscode/settings.json
Ductus.FluentDocker/Services/Impl/DockerComposeCompositeService.cs

Fixes the problems in Issue #175 by firing up the compose with --no-start and then do a proper compose up and thereby the state transition from ServiceRunningState.x -> ServiceRunningState.Starting -> ServiceRunningState.Running. Hence, all hooks is now executed properly (as with plain docker).
Hence this closes #175

Bug compose copyon

---

.vscode/settings.json
Ductus.FluentDocker/Builders/FileBuilder.cs
Ductus.FluentDocker/Builders/ImageBuilder.cs
Ductus.FluentDocker/Extensions/EnvironmentExtensions.cs
Ductus.FluentDocker/Extensions/StringExtensions.cs
Ductus.FluentDocker/Model/Builders/FileBuilder/ArgCommand.cs
Ductus.FluentDocker/Model/Builders/FileBuilder/CopyCommand.cs
Ductus.FluentDocker/Model/Builders/FileBuilder/EntrypointCommand.cs
Ductus.FluentDocker/Model/Builders/FileBuilder/EnvCommand.cs
Ductus.FluentDocker/Model/Builders/FileBuilder/FromCommand.cs
Ductus.FluentDocker/Model/Builders/FileBuilder/LabelCommand.cs
Ductus.FluentDocker/Model/Builders/FileBuilder/UserCommand.cs
Ductus.FluentDocker/Model/Builders/FileBuilder/VolumeCommand.cs

This PR adds a few enhancements to the `FileBuilder` to support a few issues and a bit more (while implementing it).
This adds the following commands:
* ENV
* ARG
* ENTRYPOINT
* LABEL
* USER
* VOLUME
Via the _Model/Builder/FileBuilder/ICommand_ structure.
Modified:
* _FROM_ to accept both platform (such as linux/amd64) and a alias name. This name may be referred using other commands.
* _COPY_ to accept chown user and group as well as _--from=alias_ to refer to a earlier build step _FROM ... AS alias_.
TODO: Add description when committing the rest.
This closes #177 when done. It also closes #178. In addition it also closes #179 when it is merged.

Add features to Docker FileBuilder

---

Ductus.FluentDocker/Builders/HostBuilder.cs
Ductus.FluentDocker/Services/Extensions/NetworkExtensions.cs
Ductus.FluentDocker/Services/Hosts.cs

Add methods:
* `FromUri` that uses a `DockerUri` to create a `IHostService`. This _uri_ is arbitary. It also support other properties (_see below_).
```cs
public HostBuilder FromUri(
DockerUri uri,
string name = null,
bool isNative = true,
bool stopWhenDisposed = false,
bool isWindowsHost = false,
string certificatePath = null) {/*...*/}
```
It will use _"sensible"_ defaults on all parameters. Most of the case the _uri_ is sufficient. For example if not providing the _certificatePath_ it will try to get it from the environment _DOCKER_CERT_PATH_. If not found in the environment, it will default to none.
* `UseHost` that takes a instantiated `IHostService` implementation.
this closes isse #185

Support for custom IHostService creation in HostBuilder

---

Ductus.FluentDocker.Tests/Common/LoggerTests.cs
Ductus.FluentDocker.Tests/Common/UnitTestingTraceListener.cs
Ductus.FluentDocker/Common/Logger.cs
Ductus.FluentDocker/Ductus.FluentDocker.csproj

The following pull request moves the logging capabilities of the library to the `Trace` implementation in dotnet.
The previous code had issues regarding the configuration which were expressed on #170. 
With this new implementation the logs generated by the library will now be available to the active `Trace.Listeners` which can then be routed to the logging framework of choice. For example, like [this](https://stackoverflow.com/questions/54537694/how-i-can-transfer-all-messages-from-system-diagnostics-trace-to-ilogger).
**Why `Trace.WriteLine` and not `Debug.WriteLine`?**
In most implementations both will redirect to the `Trace.Listeners` but on `netcoreapp2.0` the following error happens https://github.com/dotnet/runtime/issues/26781
Checklist:

Use .NET Trace for logging purposes.

---

Ductus.FluentDocker.Tests/Resources/Scripts/envtest.sh

On macOS, tests running the `envtest.sh` script would fail with a permission denied exception because the script is not exectuable:
```
System.ComponentModel.Win32Exception: Permission denied
at Interop.Sys.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setUser, UInt32 userId, UInt32 groupId, Int32& lpChildPid, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean shouldThrow)
at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
at System.Diagnostics.Process.Start()
at Ductus.FluentDocker.Executors.ProcessExecutor`2.Execute() in Ductus.FluentDocker/Executors/ProcessExecutor.cs:line 75
at Ductus.FluentDocker.Tests.ProcessTests.ProcessEnvironmentTest.ProcessShallPa …
```

Make `envtest.sh` executable and add shebang

---

Ductus.FluentDocker.Tests/CommandTests/ClientStreamCommandTests.cs
Ductus.FluentDocker.Tests/CommandTests/DockerClientCommandTests.cs
Ductus.FluentDocker.Tests/CommandTests/NetworkCommandTests.cs
Ductus.FluentDocker.Tests/FluentApiTests/FluentContainerBasicTests.cs
Ductus.FluentDocker.Tests/ServiceTests/ContainerServiceBasicTests.cs

If your test runner is configured to run several tests in parallel you will end up with bind errors because the port 40001 is already in use by another test.
> Ductus.FluentDocker.Common.FluentDockerException: Failed to start container modest_ramanujan log: Error response from daemon: driver failed programming external connectivity on endpoint modest_ramanujan (3e80ba4d0e93156184a77c573fe0b743c8e52cd590f3d58e0e4b6c9cc65cca3c): Bind for 0.0.0.0:40001 failed: port is already allocated
Also remove `ExposePort(40001, 5432)` in `PauseAndResumeShallWorkOnSingleContainer` where port mapping doesn't matter for the the test but could interfere with the `ExplicitPortMappingShouldWork` test.

Use PublishAllPorts instead of explicit port mappings in unit tests

---

Ductus.FluentDocker.Tests/ServiceTests/ContainerServiceBasicTests.cs

Without it the `ExportRunningContainerExploadedShallSucceed` test would fail (Assert.IsTrue failed) but hides the actual cause of the error:
```
Ductus.FluentDocker.Common.FluentDockerException: Exception while un-taring archive ---> SharpCompress.Common.ExtractionException: Entry is a symbolic link but ExtractionOptions.WriteSymbolicLink delegate is null
at SharpCompress.Common.ExtractionMethods.WriteEntryToFile(IEntry entry, String destinationFileName, ExtractionOptions options, Action`2 openAndWrite)
at SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)
at SharpCompress.Common.ExtractionMethods.WriteEntryToDirectory(IEntry entry, String destinationDirectory, ExtractionOptions options, Action`2 write)
at …
```

Pass throwOnError: true when calling container.Export in unit tests

---

Ductus.FluentDocker/Builders/ContainerBuilder.cs

This turns `PublishAllPorts` to `true` and also ensures that `ExposePort` and `ExposeAllPorts` are not used together since they are mutually exclusive anyway.

Add new ExposeAllPorts on the ContainerBuilder

---

Ductus.FluentDocker.MsTest/Ductus.FluentDocker.MsTest.csproj
Ductus.FluentDocker.Tests/Ductus.FluentDocker.Tests.csproj
Ductus.FluentDocker.Tests/ExtensionTests/ResourceExtensionsTests.cs
Ductus.FluentDocker/Common/FdOs.cs
Ductus.FluentDocker/Ductus.FluentDocker.csproj
Ductus.FluentDocker/Executors/ProcessExecutor.cs
Ductus.FluentDocker/Extensions/ResourceExtensions.cs
Ductus.FluentDocker/Resources/ResourceQuery.cs
global.json

* Use the .NET 5 SDK (updated in global.json)
* Define the target frameworks only once, without condition on the operating system. Now that the [Microsoft.NETFramework.ReferenceAssemblies package](https://github.com/dotnet/sdk/issues/4009) is automatically referenced by the .NET SDK, the project builds fine also on Linux and macOS.
* Remove the `COREFX` constant, use appropriate constants already defined by the SDK (NETSTANDARD1_6) where needed.
* Update all test dependencies to their latest versions
* Simplify the package dependencies, only include what's actually needed. Note that absolutely _no_ package references are needed for .NET Standard 2.0 and 2.1
Dropping support for .NET Standard 1.6 will be easy:
1. Search for the three occurrences of `#if NETSTANDARD1_6` and delete the code …

Simplify projects

---

Ductus.FluentDocker.MsTest/Ductus.FluentDocker.MsTest.csproj
Ductus.FluentDocker.Tests/Ductus.FluentDocker.Tests.csproj

Bot .NET Core 1 and .NET Core 2 have [reached end of support](https://dotnet.microsoft.com/platform/support/policy/dotnet-core). The following warnings were displayed when compiling:
> Microsoft.NET.EolTargetFrameworks.targets(28, 5): [NETSDK1138] The target framework 'netcoreapp1.1' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
> Microsoft.NET.EolTargetFrameworks.targets(28, 5): [NETSDK1138] The target framework 'netcoreapp2.0' is out of support and will not receive security updates in the future. Please refer to https://aka.ms/dotnet-core-support for more information about the support policy.
* Replace netcoreapp1.1 + netcoreapp2.0 with netstandard1.6 in …

Cleanup old target frameworks

---

Ductus.FluentDocker/Extensions/CommandExtensions.cs

The parent methods (IsDockerDnsAvailable and EmulatedNativeAddress) are both synchronous methods, so better use the sync version of GetHostEntry to avoid all the problems that will be caused by the [sync over async](https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#avoid-using-taskresult-and-taskwait) pattern.

Use GetHostEntry instead of GetHostEntryAsync

---

Ductus.FluentDocker/Extensions/CommandExtensions.cs

Using GetHostEntry instead of GetHostEntryAsync + Wait means the `SocketException` is no longer wrapped inside an `AggregateException`.
Also simplify catching the the `AggregateException` in the .NET Standard 1.6 code path by using `GetBaseException()`.

Properly catch SocketException when calling GetHostEntry

---

Ductus.FluentDocker.XUnit/Ductus.FluentDocker.XUnit.csproj
Ductus.FluentDocker.XUnit/FluentDockerTestBase.cs
Ductus.FluentDocker.XUnit/PostgresTestBase.cs
FluentDocker.sln
README.md

Feature xunit

---

Ductus.FluentDocker/Commands/Client.cs

The GetImages command do not work when a filter has been passed since it will overwrite the base switches.
This closes Issue #219

GetImages bug

---

Ductus.FluentDocker/Ductus.FluentDocker.csproj
Ductus.FluentDocker/Executors/ProcessExecutor.cs
Ductus.FluentDocker/Extensions/CommandExtensions.cs
Ductus.FluentDocker/Extensions/ResourceExtensions.cs
Ductus.FluentDocker/Resources/ResourceQuery.cs

Now that .NET Standard 1.6 target framework is removed, all the .NET Standard 1.6 specific code can be deleted.
Also remove all unnecessary package references which are actually part of .NET Standard 2.0 and Microsoft.Extensions.DependencyModel which was only used in the .NET Standard 1.6 specific code.

Remove .NET Standard 1.6 code

---

Ductus.FluentDocker/Model/Networks/NetworkType.cs

This PR adds the IPvlan NetworkType (https://docs.docker.com/network/#network-drivers). I have an IPvlan network setup which trigger the following error:
```
Unhandled exception. System.ArgumentException: Requested value 'ipvlan' was not found.
at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
at …
```

Support IPvlan networks

---

Ductus.FluentDocker/Model/Builders/FileBuilder/ExposeCommand.cs

According to Docker [documentation](https://docs.docker.com/engine/reference/builder/) EXPOSE command is delimited by spaces and not by commas and it's template looks like so: `EXPOSE <port> [<port>/<protocol>...]` This also means that a protocol can be provided so the ExposeCommand should also accept a string as input.

Fixes and improvements to ExposeCommand

---

Ductus.FluentDocker/Builders/CompositeBuilder.cs
Ductus.FluentDocker/Model/Compose/ComposeVersion.cs
Ductus.FluentDocker/Model/Compose/DockerComposeConfig.cs
Ductus.FluentDocker/Services/Impl/DockerComposeCompositeService.cs

- Added `CompositeBuilder.AssumeComposeVersion(ComposeVersion composeVersion)` method.
- Updated the logic in `DockerComposeCompositeService.ExtractNames` to separate container names with either `_` or `-`, depending on the compose version specified.
- Made `DockerComposeCompositeService` more extensible by changing the accessibility of some members from `private` to `protected`. This allows derived classes to access things such as the config and the hosts/containers collections when overriding methods.

Allow specifying compose version (V1 or V2)
