Ductus.FluentDocker.Tests/ServiceTests/ContainerServiceBasicTests.cs, Ductus.FluentDocker/Extensions/ModelExtensions.cs, Ductus.FluentDocker/Extensions/ServiceExtensions.cs
Added ability to wait for stopped state (useful in case you want to wait for jobs to finish).
=> Wait For Stopped State

Ductus.FluentDocker/Extensions/Utils/DockerBinariesResolver.cs
DockerBinariesResolver crashes if environment variable PATH contains invalid characters.
Example of wrong PATH: 'c:\folder1;c:\folder2;c:\folder3     ;'.
=> Bugfix: DockerBinariesResolver crashes.

Ductus.FluentDocker/Commands/Client.cs, Ductus.FluentDocker/Executors/Parsers/IgnoreErrorResponseParser.cs, Ductus.FluentDocker/Executors/Parsers/ProcessExitAwareResponseParser.cs
Process exit code drives if response is a success
=> Fixes copyTo/copyFrom with throwOnError: true

Ductus.FluentDocker/Services/Extensions/ContainerExtensions.cs
A new feature to wait for a specific message in container logs.
=> New feature: WaitForMessageInLogs

.editorconfig, Ductus.FluentDocker.MsTest/Ductus.FluentDocker.MsTest.csproj, Ductus.FluentDocker.Tests/FluentApiTests/FluentContainerBasicTests.cs, Ductus.FluentDocker/Builders/VolumeBuilder.cs, Ductus.FluentDocker/Ductus.FluentDocker.csproj, Ductus.FluentDocker/Fd.cs, FluentDocker.sln, GitVersion.yml, NuGet.config, appveyor.yml
Setup as per Issue #123. This is the first attempt.
=> DevOps Attempt #1 (auto push nuget + pre-release)

README.md, appveyor.yml
Make sure it won't push to nuget from a branch. Instead push nuget packages from master branch.
=> deploy on barnch master.

README.md
Updated contribution in README.md
=> Test PR builds

Ductus.FluentDocker.MsTest/Ductus.FluentDocker.MsTest.csproj, Ductus.FluentDocker.Tests/Ductus.FluentDocker.Tests.csproj, Ductus.FluentDocker.Tests/FluentApiTests/ImageBuilderTests.cs, Ductus.FluentDocker/Builders/ContainerBuilder.cs, Ductus.FluentDocker/Builders/ImageBuilder.cs, Ductus.FluentDocker/Commands/Machine.cs, Ductus.FluentDocker/Common/ResultExtensions.cs, Ductus.FluentDocker/Ductus.FluentDocker.csproj, Ductus.FluentDocker/Executors/Mappers/FdEventStreamMapper.cs, Ductus.FluentDocker/Extensions/ModelExtensions.cs, Ductus.FluentDocker/Model/Builders/FileBuilder/CmdCommand.cs, Ductus.FluentDocker/Model/Builders/FileBuilder/ShellCommand.cs, FluentDocker.Features/FluentDocker.Features.Elk/FluentDocker.Features.Elk.csproj, Tests/Tests.csproj, appveyor.yml
=> GH156: Fix ImageBuilder array parameters

Ductus.FluentDocker/Extensions/CommandExtensions.cs, appveyor.yml
=> GH158: Use host.docker.internal fqdn

Ductus.FluentDocker.Tests/Model/Containers/ContainerCreateParamsTests.cs, Ductus.FluentDocker/Model/Containers/ContainerCreateParams.cs
Implemented equivalent to docker build.
=> Add "Isolation" parameter for docker create

Ductus.FluentDocker/Builders/ContainerBuilder.cs
Allow user to specify "--ipc" within ContainerBuilder and Fluent API.
=> Add method WithIPC()

Ductus.FluentDocker.Tests/Ductus.FluentDocker.Tests.csproj, Ductus.FluentDocker.Tests/Model/Builders/CmdCommandTests.cs, Ductus.FluentDocker.Tests/Model/Builders/ContainerBuilderConfigTests.cs, Ductus.FluentDocker.Tests/ServiceTests/NetworkServiceTests.cs, Ductus.FluentDocker/Builders/ContainerBuilder.cs, Ductus.FluentDocker/Model/Builders/ContainerBuilderConfig.cs, Ductus.FluentDocker/Model/Builders/FileBuilder/CmdCommand.cs, Ductus.FluentDocker/Model/Builders/NetworkWithAlias.cs, Ductus.FluentDocker/Model/Containers/ContainerCreateParams.cs, Ductus.FluentDocker/Services/INetworkService.cs, Ductus.FluentDocker/Services/Impl/DockerNetworkService.cs, appveyor.yml
A redo of #172 to avoid creating API incompatibilities. I mainly made a new PR because I just started from scratch and didn't want to have to deal with reworking the other branch.
I still want to add some tests but wanted to get an initial implementation down. I know the opposite of TDD 😄
=> Add UseNetworkWithAlias() on ContainerBuilder

Ductus.FluentDocker.Tests/Model/Builders/FileBuilder/CmdCommandTests.cs, Ductus.FluentDocker/Model/Builders/FileBuilder/EntrypointCommand.cs, Ductus.FluentDocker/Model/Builders/FileBuilder/FromCommand.cs, Ductus.FluentDocker/Model/Builders/FileBuilder/ShellCommand.cs
* From with Alias did not render correctly, closes #181 
* Shell & Environment did not render the arguments correctly, closes #183
=> misc fixes for filebuilder

Ductus.FluentDocker.MsTest/Ductus.FluentDocker.MsTest.csproj, Ductus.FluentDocker.Tests/FluentApiTests/FluentContainerBasicTests.cs, Ductus.FluentDocker/Ductus.FluentDocker.csproj, appveyor.yml
Re-add version metadata to assemblies
=> fix version metadata

Ductus.FluentDocker.MsTest/Ductus.FluentDocker.MsTest.csproj, Ductus.FluentDocker.XUnit/Ductus.FluentDocker.XUnit.csproj, Ductus.FluentDocker/Ductus.FluentDocker.csproj
Since sharpcompress do no longer support it
=> Remove netstandard1.6

Ductus.FluentDocker.Tests/ExtensionTests/ConversionExtensionTests.cs, Ductus.FluentDocker.Tests/FluentApiTests/FluentContainerBasicTests.cs, Ductus.FluentDocker/Builders/ContainerBuilder.cs, Ductus.FluentDocker/Extensions/ConversionExtension.cs, Ductus.FluentDocker/Model/Containers/ContainerCreateParams.cs
=> Add fluent memory limit

Ductus.FluentDocker/Builders/ContainerBuilder.cs
Add a `WithMemorySwap` option to container builder
=> Add WithMemorySwap to Container Builder

Ductus.FluentDocker.Tests/ServiceTests/ContainerServiceBasicTests.cs, Ductus.FluentDocker/Commands/Client.cs, Ductus.FluentDocker/Services/IHostService.cs, Ductus.FluentDocker/Services/Impl/DockerHostService.cs
This fixes issue #249. I also added the option to use multiple filters. This change is breaking though for the `Images` command.
=> Fixed issue: 249 + implemented multiple filters

Ductus.FluentDocker/Model/Containers/ContainerCreateParams.cs
https://github.com/mariotoffia/FluentDocker/issues/259
=> Fix for --add-host issue

Ductus.FluentDocker/Services/Impl/DockerContainerService.cs
Fix for https://github.com/mariotoffia/FluentDocker/issues/253
=> Get fresh state on start

Ductus.FluentDocker.Tests/CommandTests/ComposeCommandTests.cs, Ductus.FluentDocker.Tests/Ductus.FluentDocker.Tests.csproj, Ductus.FluentDocker.Tests/FluentApiTests/FluentDockerComposeTests.cs, Ductus.FluentDocker.Tests/Resources/ComposeTests/RabbitMQ/docker-compose.yml, Ductus.FluentDocker/Builders/CompositeBuilder.cs, Ductus.FluentDocker/Commands/Compose.cs, Ductus.FluentDocker/Model/Compose/DockerComposeConfig.cs, Ductus.FluentDocker/Services/Impl/DockerComposeCompositeService.cs
Added WaitForHealthy() and WaitForHealthy(int waitTimeoutSeconds) API methods to CompositeBuilder via `--wait` and `--wait-timeout` docker compose flags.
Added two basic tests to check the functionality on low and high levels.
=> Added --wait and --wait-timeout flags support
